spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Bakugan03
    url: jdbc:postgresql://localhost:5432/usersandadmins

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
